### ISSUE TITLE
'WebDriver' object has no attribute 'switch_to_alert'

### ISSUE THREAD

**Issue by decodar** [nateshmbhat/webbot#62]
Hi Natesh - I've been using webbot to automate some browser tasks and recently moved my code to a new mac.  I am getting an attribute error on the web=Browser() code - the Chrome window launches, but then nothing happens, and I get the attribute error.  I think the problem is either with Chrome (so I reinstalled) or in the Selenium code you wrapped (saving me lots of reading and time - thank you!), but wanted to check with you to see if there was a simple solution.   

Thanks!

Darrin

**Comment by questjay** [comment]
me too

**Comment by decodar** [comment]
No resolution - I converted to selenium.

**Comment by rpgraham** [comment]
I have the same issue with webbot and selenium 4.0.0 on a new Mac; but I don't know how to undergrade to selenium 3.141.0.  Can you give me some tips?

**Comment by questjay** [comment]
@rpgraham just `pip uninstall selenium` to uninstall then `pip install selenium==3.141.0`  remember you have to uninstall to undergrade.

**Comment by rpgraham** [comment]
Thanks so much!  That took care of it.

**Comment by DillonB07** [comment]
Solved in #80 !

Installing webbot again should fix everything!

**Comment by Pallav2905-py** [comment]
Thanks, it worked for me <3

> @rpgraham just `pip uninstall selenium` to uninstall then `pip install selenium==3.141.0` remember you have to uninstall to undergrade.

**Comment by Leberworschd** [comment]
Thanks a lot! I was already frustrated. This worked!!!

@rpgraham just pip uninstall selenium to uninstall then pip install selenium==3.141.0 remember you have to uninstall to undergrade.

**Comment by pedrobritobr** [comment]
> @rpgraham just `pip uninstall selenium` to uninstall then `pip install selenium==3.141.0` remember you have to uninstall to undergrade.

Works for me, thanks!

**Comment by lulucandy-us** [comment]
I have the same problem. I followed the uninstall and install commands to undergrade the selenium to 3.141.0, however the error still there. the version of my webbot is 0.34. Any other thing need to take care? Does it also relevant to the chromedriver version?

**Comment by Raksh710** [comment]
In the latest version of selenium (I downloaded it the day before yesterday i.e. June 4, 2022), you can try using this:
```
alert = driver.switch_to.alert
alert.accept()
```

**Comment by kashagit** [comment]
@Raksh710 I am trying this code from webbot 
import Browser 
web = Browser() and when I added  driver.switch_to.alert it says driver not found
